INSERT INTO `questions` (`category`, `difficulty`, `question_text`, `emojis`, `options`, `correct_answer`, `explanation`) VALUES
('math', 'easy', '11 - 4 = ?', NULL, NULL, '7', '11 - 4 equals 7.'),
('math', 'easy', '24 - 16 = ?', NULL, NULL, '8', '24 - 16 equals 8.'),
('math', 'easy', '9 + 2 = ?', NULL, NULL, '11', '9 + 2 equals 11.'),
('math', 'easy', '29 - 22 = ?', NULL, NULL, '7', '29 - 22 equals 7.'),
('math', 'easy', '4 - 2 = ?', NULL, NULL, '2', '4 - 2 equals 2.'),
('math', 'easy', '18 - 10 = ?', NULL, NULL, '8', '18 - 10 equals 8.'),
('math', 'easy', '6 + 7 = ?', NULL, NULL, '13', '6 + 7 equals 13.'),
('math', 'easy', '24 - 24 = ?', NULL, NULL, '0', '24 - 24 equals 0.'),
('math', 'easy', '7 - 5 = ?', NULL, NULL, '2', '7 - 5 equals 2.'),
('math', 'easy', '14 + 14 = ?', NULL, NULL, '28', '14 + 14 equals 28.'),
('math', 'easy', '22 - 3 = ?', NULL, NULL, '19', '22 - 3 equals 19.'),
('math', 'easy', '9 - 5 = ?', NULL, NULL, '4', '9 - 5 equals 4.'),
('math', 'easy', '5 + 7 = ?', NULL, NULL, '12', '5 + 7 equals 12.'),
('math', 'easy', '30 - 2 = ?', NULL, NULL, '28', '30 - 2 equals 28.'),
('math', 'easy', '23 + 26 = ?', NULL, NULL, '49', '23 + 26 equals 49.'),
('math', 'easy', '24 + 25 = ?', NULL, NULL, '49', '24 + 25 equals 49.'),
('math', 'easy', '2 + 10 = ?', NULL, NULL, '12', '2 + 10 equals 12.'),
('math', 'easy', '28 + 22 = ?', NULL, NULL, '50', '28 + 22 equals 50.'),
('math', 'easy', '23 - 10 = ?', NULL, NULL, '13', '23 - 10 equals 13.'),
('math', 'easy', '22 - 11 = ?', NULL, NULL, '11', '22 - 11 equals 11.'),
('math', 'easy', '20 - 4 = ?', NULL, NULL, '16', '20 - 4 equals 16.'),
('math', 'easy', '9 + 17 = ?', NULL, NULL, '26', '9 + 17 equals 26.'),
('math', 'easy', '13 + 9 = ?', NULL, NULL, '22', '13 + 9 equals 22.'),
('math', 'easy', '14 + 19 = ?', NULL, NULL, '33', '14 + 19 equals 33.'),
('math', 'easy', '25 - 25 = ?', NULL, NULL, '0', '25 - 25 equals 0.'),
('math', 'easy', '14 - 10 = ?', NULL, NULL, '4', '14 - 10 equals 4.'),
('math', 'easy', '27 + 26 = ?', NULL, NULL, '53', '27 + 26 equals 53.'),
('math', 'easy', '4 + 13 = ?', NULL, NULL, '17', '4 + 13 equals 17.'),
('math', 'easy', '21 - 9 = ?', NULL, NULL, '12', '21 - 9 equals 12.'),
('math', 'easy', '16 - 3 = ?', NULL, NULL, '13', '16 - 3 equals 13.'),
('math', 'easy', '23 - 14 = ?', NULL, NULL, '9', '23 - 14 equals 9.'),
('math', 'easy', '17 - 3 = ?', NULL, NULL, '14', '17 - 3 equals 14.'),
('math', 'easy', '23 + 27 = ?', NULL, NULL, '50', '23 + 27 equals 50.'),
('math', 'easy', '17 + 25 = ?', NULL, NULL, '42', '17 + 25 equals 42.'),
('math', 'easy', '16 + 21 = ?', NULL, NULL, '37', '16 + 21 equals 37.'),
('math', 'easy', '30 + 25 = ?', NULL, NULL, '55', '30 + 25 equals 55.'),
('math', 'easy', '22 - 8 = ?', NULL, NULL, '14', '22 - 8 equals 14.'),
('math', 'easy', '29 - 1 = ?', NULL, NULL, '28', '29 - 1 equals 28.'),
('math', 'easy', '19 - 4 = ?', NULL, NULL, '15', '19 - 4 equals 15.'),
('math', 'easy', '5 - 4 = ?', NULL, NULL, '1', '5 - 4 equals 1.'),
('math', 'medium', '8 × 5 = ?', NULL, NULL, '40', '8 multiplied by 5 is 40.'),
('math', 'medium', '24 ÷ 3 = ?', NULL, NULL, '8', '24 divided by 3 is 8.'),
('math', 'medium', '12 × 9 = ?', NULL, NULL, '108', '12 multiplied by 9 is 108.'),
('math', 'medium', '3 × 8 = ?', NULL, NULL, '24', '3 multiplied by 8 is 24.'),
('math', 'medium', '7 × 11 = ?', NULL, NULL, '77', '7 multiplied by 11 is 77.'),
('math', 'medium', '84 ÷ 7 = ?', NULL, NULL, '12', '84 divided by 7 is 12.'),
('math', 'medium', '10 × 4 = ?', NULL, NULL, '40', '10 multiplied by 4 is 40.'),
('math', 'medium', '3 × 6 = ?', NULL, NULL, '18', '3 multiplied by 6 is 18.'),
('math', 'medium', '72 ÷ 8 = ?', NULL, NULL, '9', '72 divided by 8 is 9.'),
('math', 'medium', '7 × 12 = ?', NULL, NULL, '84', '7 multiplied by 12 is 84.'),
('math', 'medium', '4 × 7 = ?', NULL, NULL, '28', '4 multiplied by 7 is 28.'),
('math', 'medium', '7 × 2 = ?', NULL, NULL, '14', '7 multiplied by 2 is 14.'),
('math', 'medium', '3 × 12 = ?', NULL, NULL, '36', '3 multiplied by 12 is 36.'),
('math', 'medium', '8 × 11 = ?', NULL, NULL, '88', '8 multiplied by 11 is 88.'),
('math', 'medium', '3 × 4 = ?', NULL, NULL, '12', '3 multiplied by 4 is 12.'),
('math', 'medium', '50 ÷ 10 = ?', NULL, NULL, '5', '50 divided by 10 is 5.'),
('math', 'medium', '8 × 8 = ?', NULL, NULL, '64', '8 multiplied by 8 is 64.'),
('math', 'medium', '60 ÷ 10 = ?', NULL, NULL, '6', '60 divided by 10 is 6.'),
('math', 'medium', '6 × 2 = ?', NULL, NULL, '12', '6 multiplied by 2 is 12.'),
('math', 'medium', '45 ÷ 9 = ?', NULL, NULL, '5', '45 divided by 9 is 5.'),
('math', 'medium', '60 ÷ 12 = ?', NULL, NULL, '5', '60 divided by 12 is 5.'),
('math', 'medium', '24 ÷ 4 = ?', NULL, NULL, '6', '24 divided by 4 is 6.'),
('math', 'medium', '48 ÷ 12 = ?', NULL, NULL, '4', '48 divided by 12 is 4.'),
('math', 'medium', '3 × 10 = ?', NULL, NULL, '30', '3 multiplied by 10 is 30.'),
('math', 'medium', '7 × 3 = ?', NULL, NULL, '21', '7 multiplied by 3 is 21.'),
('math', 'medium', '110 ÷ 10 = ?', NULL, NULL, '11', '110 divided by 10 is 11.'),
('math', 'medium', '10 × 12 = ?', NULL, NULL, '120', '10 multiplied by 12 is 120.'),
('math', 'medium', '12 ÷ 6 = ?', NULL, NULL, '2', '12 divided by 6 is 2.'),
('math', 'medium', '8 × 11 = ?', NULL, NULL, '88', '8 multiplied by 11 is 88.'),
('math', 'medium', '2 × 6 = ?', NULL, NULL, '12', '2 multiplied by 6 is 12.'),
('math', 'medium', '54 ÷ 9 = ?', NULL, NULL, '6', '54 divided by 9 is 6.'),
('math', 'medium', '15 ÷ 3 = ?', NULL, NULL, '5', '15 divided by 3 is 5.'),
('math', 'medium', '27 ÷ 9 = ?', NULL, NULL, '3', '27 divided by 9 is 3.'),
('math', 'medium', '84 ÷ 12 = ?', NULL, NULL, '7', '84 divided by 12 is 7.'),
('math', 'medium', '11 × 10 = ?', NULL, NULL, '110', '11 multiplied by 10 is 110.'),
('math', 'medium', '10 × 9 = ?', NULL, NULL, '90', '10 multiplied by 9 is 90.'),
('math', 'medium', '11 × 10 = ?', NULL, NULL, '110', '11 multiplied by 10 is 110.'),
('math', 'medium', '3 × 3 = ?', NULL, NULL, '9', '3 multiplied by 3 is 9.'),
('math', 'medium', '27 ÷ 3 = ?', NULL, NULL, '9', '27 divided by 3 is 9.'),
('math', 'medium', '7 × 9 = ?', NULL, NULL, '63', '7 multiplied by 9 is 63.'),
('math', 'hard', '50% of 150 = ?', NULL, NULL, '70', '50% of 150 is 70.'),
('math', 'hard', '10% of 460 = ?', NULL, NULL, '40', '10% of 460 is 40.'),
('math', 'hard', '10% of 300 = ?', NULL, NULL, '30', '10% of 300 is 30.'),
('math', 'hard', '10% of 480 = ?', NULL, NULL, '40', '10% of 480 is 40.'),
('math', 'hard', '50% of 120 = ?', NULL, NULL, '60', '50% of 120 is 60.'),
('math', 'hard', '25% of 230 = ?', NULL, NULL, '50', '25% of 230 is 50.'),
('math', 'hard', '50% of 400 = ?', NULL, NULL, '200', '50% of 400 is 200.'),
('math', 'hard', '50% of 220 = ?', NULL, NULL, '110', '50% of 220 is 110.'),
('math', 'hard', '10% of 360 = ?', NULL, NULL, '30', '10% of 360 is 30.'),
('math', 'hard', '10% of 360 = ?', NULL, NULL, '30', '10% of 360 is 30.'),
('math', 'hard', '50% of 450 = ?', NULL, NULL, '220', '50% of 450 is 220.'),
('math', 'hard', '20% of 100 = ?', NULL, NULL, '20', '20% of 100 is 20.'),
('math', 'hard', '50% of 250 = ?', NULL, NULL, '120', '50% of 250 is 120.'),
('math', 'hard', '20% of 380 = ?', NULL, NULL, '70', '20% of 380 is 70.'),
('math', 'hard', '25% of 300 = ?', NULL, NULL, '70', '25% of 300 is 70.'),
('math', 'hard', '50% of 280 = ?', NULL, NULL, '140', '50% of 280 is 140.'),
('math', 'hard', '25% of 430 = ?', NULL, NULL, '100', '25% of 430 is 100.'),
('math', 'hard', '25% of 370 = ?', NULL, NULL, '90', '25% of 370 is 90.'),
('math', 'hard', '25% of 270 = ?', NULL, NULL, '60', '25% of 270 is 60.'),
('math', 'hard', '10% of 430 = ?', NULL, NULL, '40', '10% of 430 is 40.'),
('geography', 'easy', 'What is the capital of Vanuatu?', NULL, '["Sofia", "New Delhi", "Port Vila", "Canberra"]', 'Port Vila', 'Port Vila is the capital of Vanuatu.'),
('geography', 'easy', 'What is the capital of Paraguay?', NULL, '["Asuncion", "Montevideo", "Paris", "Port-au-Prince"]', 'Asuncion', 'Asuncion is the capital of Paraguay.'),
('geography', 'easy', 'What is the capital of Myanmar?', NULL, '["Wellington", "Havana", "Naypyidaw", "Seoul"]', 'Naypyidaw', 'Naypyidaw is the capital of Myanmar.'),
('geography', 'easy', 'What is the capital of Bangladesh?', NULL, '["Bern", "Porto-Novo", "Dhaka", "Paramaribo"]', 'Dhaka', 'Dhaka is the capital of Bangladesh.'),
('geography', 'easy', 'What is the capital of Botswana?', NULL, '["New Delhi", "Bogota", "Gaborone", "Kabul"]', 'Gaborone', 'Gaborone is the capital of Botswana.'),
('geography', 'easy', 'What is the capital of Venezuela?', NULL, '["Beijing", "Bogota", "Ankara", "Caracas"]', 'Caracas', 'Caracas is the capital of Venezuela.'),
('geography', 'easy', 'What is the capital of India?', NULL, '["San Salvador", "Ngerulmud", "Panama City", "New Delhi"]', 'New Delhi', 'New Delhi is the capital of India.'),
('geography', 'easy', 'What is the capital of Bahamas?', NULL, '["Nassau", "Naypyidaw", "Dushanbe", "Guatemala City"]', 'Nassau', 'Nassau is the capital of Bahamas.'),
('geography', 'easy', 'What is the capital of Bahrain?', NULL, '["Warsaw", "Guatemala City", "Djibouti", "Manama"]', 'Manama', 'Manama is the capital of Bahrain.'),
('geography', 'easy', 'What is the capital of Montenegro?', NULL, '["Podgorica", "Antananarivo", "Rabat", "Tashkent"]', 'Podgorica', 'Podgorica is the capital of Montenegro.'),
('geography', 'easy', 'What is the capital of Mali?', NULL, '["Lima", "Paris", "Minsk", "Bamako"]', 'Bamako', 'Bamako is the capital of Mali.'),
('geography', 'easy', 'What is the capital of United Kingdom?', NULL, '["Tokyo", "Kabul", "London", "Minsk"]', 'London', 'London is the capital of United Kingdom.'),
('geography', 'easy', 'What is the capital of Kiribati?', NULL, '["Monaco", "South Tarawa", "Nassau", "Kuwait City"]', 'South Tarawa', 'South Tarawa is the capital of Kiribati.'),
('geography', 'easy', 'What is the capital of Lebanon?', NULL, '["Beirut", "Port Louis", "Santiago", "Minsk"]', 'Beirut', 'Beirut is the capital of Lebanon.'),
('geography', 'easy', 'What is the capital of Bhutan?', NULL, '["Kabul", "Banjul", "Tirana", "Thimphu"]', 'Thimphu', 'Thimphu is the capital of Bhutan.'),
('geography', 'easy', 'What is the capital of Guyana?', NULL, '["Panama City", "George Town", "Warsaw", "Tehran"]', 'George Town', 'George Town is the capital of Guyana.'),
('geography', 'easy', 'What is the capital of Malawi?', NULL, '["Libreville", "Lilongwe", "Bern", "Lusaka"]', 'Lilongwe', 'Lilongwe is the capital of Malawi.'),
('geography', 'easy', 'What is the capital of Denmark?', NULL, '["Nouakchott", "Panama City", "Dushanbe", "Copenhagen"]', 'Copenhagen', 'Copenhagen is the capital of Denmark.'),
('geography', 'easy', 'What is the capital of New Zealand?', NULL, '["Doha", "Wellington", "Libreville", "Amman"]', 'Wellington', 'Wellington is the capital of New Zealand.'),
('geography', 'easy', 'What is the capital of Rwanda?', NULL, '["San Salvador", "Podgorica", "Kigali", "Dakar"]', 'Kigali', 'Kigali is the capital of Rwanda.'),
('geography', 'easy', 'What is the capital of Mongolia?', NULL, '["Lisbon", "Berlin", "Ulaanbaatar", "Quito"]', 'Ulaanbaatar', 'Ulaanbaatar is the capital of Mongolia.'),
('geography', 'easy', 'What is the capital of Portugal?', NULL, '["George Town", "Tashkent", "San Jose", "Lisbon"]', 'Lisbon', 'Lisbon is the capital of Portugal.'),
('geography', 'easy', 'What is the capital of Kuwait?', NULL, '["Ouagadougou", "Kuwait City", "Tirana", "Caracas"]', 'Kuwait City', 'Kuwait City is the capital of Kuwait.'),
('geography', 'easy', 'What is the capital of Israel?', NULL, '["Jerusalem", "Bangkok", "San Salvador", "Naypyidaw"]', 'Jerusalem', 'Jerusalem is the capital of Israel.'),
('geography', 'easy', 'What is the capital of Uzbekistan?', NULL, '["Algiers", "Stockholm", "Tashkent", "London"]', 'Tashkent', 'Tashkent is the capital of Uzbekistan.'),
('geography', 'easy', 'What is the capital of Fiji?', NULL, '["Kuala Lumpur", "Kathmandu", "Suva", "Moscow"]', 'Suva', 'Suva is the capital of Fiji.'),
('geography', 'easy', 'What is the capital of Colombia?', NULL, '["Bogota", "George Town", "Brussels", "Algiers"]', 'Bogota', 'Bogota is the capital of Colombia.'),
('geography', 'easy', 'What is the capital of Honduras?', NULL, '["Accra", "Canberra", "Kuala Lumpur", "Tegucigalpa"]', 'Tegucigalpa', 'Tegucigalpa is the capital of Honduras.'),
('geography', 'easy', 'What is the capital of Mexico?', NULL, '["Taipei", "Warsaw", "Cairo", "Mexico City"]', 'Mexico City', 'Mexico City is the capital of Mexico.'),
('geography', 'easy', 'What is the capital of Guatemala?', NULL, '["Mogadishu", "Kyiv", "Hanoi", "Guatemala City"]', 'Guatemala City', 'Guatemala City is the capital of Guatemala.'),
('geography', 'easy', 'What is the capital of Belarus?', NULL, '["Khartoum", "Mexico City", "Minsk", "Kathmandu"]', 'Minsk', 'Minsk is the capital of Belarus.'),
('geography', 'easy', 'What is the capital of Nigeria?', NULL, '["Singapore", "Abuja", "Vientiane", "Monaco"]', 'Abuja', 'Abuja is the capital of Nigeria.'),
('geography', 'easy', 'What is the capital of Somalia?', NULL, '["Guatemala City", "Conakry", "Mogadishu", "Banjul"]', 'Mogadishu', 'Mogadishu is the capital of Somalia.'),
('geography', 'easy', 'What is the capital of Vatican City?', NULL, '["Vatican City", "Amman", "Port Louis", "Panama City"]', 'Vatican City', 'Vatican City is the capital of Vatican City.'),
('geography', 'easy', 'What is the capital of Cyprus?', NULL, '["Tallinn", "Jakarta", "Bangkok", "Nicosia"]', 'Nicosia', 'Nicosia is the capital of Cyprus.'),
('geography', 'easy', 'What is the capital of Qatar?', NULL, '["Dhaka", "Doha", "Budapest", "Belmopan"]', 'Doha', 'Doha is the capital of Qatar.'),
('geography', 'easy', 'What is the capital of Uruguay?', NULL, '["Montevideo", "Pyongyang", "Stockholm", "Jakarta"]', 'Montevideo', 'Montevideo is the capital of Uruguay.'),
('geography', 'easy', 'What is the capital of Ethiopia?', NULL, '["Podgorica", "Paramaribo", "Islamabad", "Addis Ababa"]', 'Addis Ababa', 'Addis Ababa is the capital of Ethiopia.'),
('geography', 'easy', 'What is the capital of Ecuador?', NULL, '["Quito", "Dodoma", "Stockholm", "Kigali"]', 'Quito', 'Quito is the capital of Ecuador.'),
('geography', 'easy', 'What is the capital of Cambodia?', NULL, '["Phnom Penh", "Colombo", "Mexico City", "New Delhi"]', 'Phnom Penh', 'Phnom Penh is the capital of Cambodia.'),
('geography', 'easy', 'What is the capital of Chad?', NULL, '["Harare", "N''Djamena", "Male", "Gitega"]', 'N''Djamena', 'N''Djamena is the capital of Chad.'),
('geography', 'easy', 'What is the capital of Suriname?', NULL, '["Gitega", "Vaduz", "Paramaribo", "Tirana"]', 'Paramaribo', 'Paramaribo is the capital of Suriname.'),
('geography', 'easy', 'What is the capital of Djibouti?', NULL, '["Oslo", "Djibouti", "Port Moresby", "Paris"]', 'Djibouti', 'Djibouti is the capital of Djibouti.'),
('geography', 'easy', 'What is the capital of Tajikistan?', NULL, '["Panama City", "Ottawa", "Dodoma", "Dushanbe"]', 'Dushanbe', 'Dushanbe is the capital of Tajikistan.'),
('geography', 'easy', 'What is the capital of Mauritius?', NULL, '["Oslo", "Kuwait City", "Dushanbe", "Port Louis"]', 'Port Louis', 'Port Louis is the capital of Mauritius.'),
('geography', 'easy', 'What is the capital of Finland?', NULL, '["Maseru", "Ulaanbaatar", "Kabul", "Helsinki"]', 'Helsinki', 'Helsinki is the capital of Finland.'),
('geography', 'easy', 'What is the capital of Bulgaria?', NULL, '["Singapore", "Santiago", "Mexico City", "Sofia"]', 'Sofia', 'Sofia is the capital of Bulgaria.'),
('geography', 'easy', 'What is the capital of Oman?', NULL, '["Brasilia", "Podgorica", "Muscat", "Phnom Penh"]', 'Muscat', 'Muscat is the capital of Oman.'),
('geography', 'easy', 'What is the capital of Zambia?', NULL, '["Ottawa", "Kuwait City", "Stockholm", "Lusaka"]', 'Lusaka', 'Lusaka is the capital of Zambia.'),
('geography', 'easy', 'What is the capital of Iceland?', NULL, '["Copenhagen", "Funafuti", "Reykjavik", "Mogadishu"]', 'Reykjavik', 'Reykjavik is the capital of Iceland.'),
('geography', 'medium', 'What is the capital of Germany?', NULL, '["Berlin", "Athens", "Banjul", "Helsinki"]', 'Berlin', 'Berlin is the capital of Germany.'),
('geography', 'medium', 'What is the capital of Peru?', NULL, '["Lima", "Madrid", "Cairo", "Bangkok"]', 'Lima', 'Lima is the capital of Peru.'),
('geography', 'medium', 'What is the capital of Panama?', NULL, '["Riyadh", "Panama City", "Port-au-Prince", "Baghdad"]', 'Panama City', 'Panama City is the capital of Panama.'),
('geography', 'medium', 'What is the capital of Malta?', NULL, '["Male", "Valletta", "Taipei", "Yerevan"]', 'Valletta', 'Valletta is the capital of Malta.'),
('geography', 'medium', 'What is the capital of Italy?', NULL, '["Lima", "Jakarta", "Rome", "Ngerulmud"]', 'Rome', 'Rome is the capital of Italy.'),
('geography', 'medium', 'What is the capital of Hungary?', NULL, '["Santiago", "Budapest", "Ouagadougou", "Harare"]', 'Budapest', 'Budapest is the capital of Hungary.'),
('geography', 'medium', 'What is the capital of Kyrgyzstan?', NULL, '["Amman", "Bishkek", "Port Moresby", "Kingston"]', 'Bishkek', 'Bishkek is the capital of Kyrgyzstan.'),
('geography', 'medium', 'What is the capital of Togo?', NULL, '["Hanoi", "Belgrade", "Lome", "Jakarta"]', 'Lome', 'Lome is the capital of Togo.'),
('geography', 'medium', 'What is the capital of Niger?', NULL, '["Belmopan", "Niamey", "Hanoi", "Bangkok"]', 'Niamey', 'Niamey is the capital of Niger.'),
('geography', 'medium', 'What is the capital of Algeria?', NULL, '["Windhoek", "Porto-Novo", "Algiers", "Ouagadougou"]', 'Algiers', 'Algiers is the capital of Algeria.'),
('geography', 'medium', 'What is the capital of France?', NULL, '["Guatemala City", "Paris", "Manila", "Pretoria"]', 'Paris', 'Paris is the capital of France.'),
('geography', 'medium', 'What is the capital of Belgium?', NULL, '["Dhaka", "Port Moresby", "Brussels", "Sofia"]', 'Brussels', 'Brussels is the capital of Belgium.'),
('geography', 'medium', 'What is the capital of Liechtenstein?', NULL, '["Naypyidaw", "Gaborone", "Seoul", "Vaduz"]', 'Vaduz', 'Vaduz is the capital of Liechtenstein.'),
('geography', 'medium', 'What is the capital of Haiti?', NULL, '["Copenhagen", "Port-au-Prince", "Dodoma", "Bogota"]', 'Port-au-Prince', 'Port-au-Prince is the capital of Haiti.'),
('geography', 'medium', 'What is the capital of Canada?', NULL, '["Dodoma", "Pretoria", "Nouakchott", "Ottawa"]', 'Ottawa', 'Ottawa is the capital of Canada.'),
('geography', 'medium', 'What is the capital of Palau?', NULL, '["Beirut", "Lilongwe", "Bogota", "Ngerulmud"]', 'Ngerulmud', 'Ngerulmud is the capital of Palau.'),
('geography', 'medium', 'What is the capital of Greece?', NULL, '["Tehran", "Addis Ababa", "Accra", "Athens"]', 'Athens', 'Athens is the capital of Greece.'),
('geography', 'medium', 'What is the capital of Morocco?', NULL, '["Yerevan", "Brazzaville", "Manama", "Rabat"]', 'Rabat', 'Rabat is the capital of Morocco.'),
('geography', 'medium', 'What is the capital of Laos?', NULL, '["Ulaanbaatar", "Dodoma", "Dublin", "Vientiane"]', 'Vientiane', 'Vientiane is the capital of Laos.'),
('geography', 'medium', 'What is the capital of Georgia?', NULL, '["Tbilisi", "Phnom Penh", "Tehran", "Sucre"]', 'Tbilisi', 'Tbilisi is the capital of Georgia.'),
('geography', 'medium', 'What is the capital of Luxembourg?', NULL, '["Luxembourg", "Kampala", "Astana", "Riyadh"]', 'Luxembourg', 'Luxembourg is the capital of Luxembourg.'),
('geography', 'medium', 'What is the capital of Cuba?', NULL, '["Dublin", "Libreville", "Havana", "Damascus"]', 'Havana', 'Havana is the capital of Cuba.'),
('geography', 'medium', 'What is the capital of South Africa?', NULL, '["Kigali", "Pretoria", "Doha", "Colombo"]', 'Pretoria', 'Pretoria is the capital of South Africa.'),
('geography', 'medium', 'What is the capital of Senegal?', NULL, '["Colombo", "Dakar", "Baku", "Vientiane"]', 'Dakar', 'Dakar is the capital of Senegal.'),
('geography', 'medium', 'What is the capital of Burundi?', NULL, '["Gitega", "Bangkok", "Vaduz", "Port Moresby"]', 'Gitega', 'Gitega is the capital of Burundi.'),
('geography', 'medium', 'What is the capital of Madagascar?', NULL, '["Conakry", "Luxembourg", "Maputo", "Antananarivo"]', 'Antananarivo', 'Antananarivo is the capital of Madagascar.'),
('geography', 'medium', 'What is the capital of Liberia?', NULL, '["Montevideo", "Zagreb", "Monrovia", "Nicosia"]', 'Monrovia', 'Monrovia is the capital of Liberia.'),
('geography', 'medium', 'What is the capital of Norway?', NULL, '["Libreville", "Oslo", "Tbilisi", "New Delhi"]', 'Oslo', 'Oslo is the capital of Norway.'),
('geography', 'medium', 'What is the capital of Romania?', NULL, '["Tripoli", "Ashgabat", "Bucharest", "Kabul"]', 'Bucharest', 'Bucharest is the capital of Romania.'),
('geography', 'medium', 'What is the capital of Dominica?', NULL, '["Roseau", "Kyiv", "Tehran", "Ulaanbaatar"]', 'Roseau', 'Roseau is the capital of Dominica.'),
('geography', 'medium', 'What is the capital of Lesotho?', NULL, '["Ouagadougou", "Madrid", "Port Louis", "Maseru"]', 'Maseru', 'Maseru is the capital of Lesotho.'),
('geography', 'medium', 'What is the capital of Gabon?', NULL, '["Jakarta", "Rabat", "Libreville", "Prague"]', 'Libreville', 'Libreville is the capital of Gabon.'),
('geography', 'medium', 'What is the capital of Austria?', NULL, '["Vientiane", "Jerusalem", "Vienna", "Kathmandu"]', 'Vienna', 'Vienna is the capital of Austria.'),
('geography', 'medium', 'What is the capital of Estonia?', NULL, '["Rome", "Beirut", "Bogota", "Tallinn"]', 'Tallinn', 'Tallinn is the capital of Estonia.'),
('geography', 'medium', 'What is the capital of Bolivia?', NULL, '["Moscow", "Amman", "Canberra", "Sucre"]', 'Sucre', 'Sucre is the capital of Bolivia.'),
('geography', 'medium', 'What is the capital of Costa Rica?', NULL, '["Prague", "San Jose", "Nairobi", "Sucre"]', 'San Jose', 'San Jose is the capital of Costa Rica.'),
('geography', 'medium', 'What is the capital of Yemen?', NULL, '["Brussels", "Ljubljana", "Nairobi", "Sana''a"]', 'Sana''a', 'Sana''a is the capital of Yemen.'),
('geography', 'medium', 'What is the capital of Congo?', NULL, '["Islamabad", "Montevideo", "Ottawa", "Brazzaville"]', 'Brazzaville', 'Brazzaville is the capital of Congo.'),
('geography', 'medium', 'What is the capital of Taiwan?', NULL, '["Tashkent", "Taipei", "Helsinki", "Kyiv"]', 'Taipei', 'Taipei is the capital of Taiwan.'),
('geography', 'medium', 'What is the capital of Iran?', NULL, '["Tehran", "Tallinn", "Maputo", "Washington D.C."]', 'Tehran', 'Tehran is the capital of Iran.'),
('geography', 'medium', 'What is the capital of Czech Republic?', NULL, '["Quito", "Prague", "Bern", "Beirut"]', 'Prague', 'Prague is the capital of Czech Republic.'),
('geography', 'medium', 'What is the capital of Pakistan?', NULL, '["Islamabad", "Tokyo", "Washington D.C.", "Vaduz"]', 'Islamabad', 'Islamabad is the capital of Pakistan.'),
('geography', 'medium', 'What is the capital of Chile?', NULL, '["Harare", "Santiago", "Algiers", "Tehran"]', 'Santiago', 'Santiago is the capital of Chile.'),
('geography', 'medium', 'What is the capital of Sri Lanka?', NULL, '["Libreville", "Managua", "Colombo", "Amsterdam"]', 'Colombo', 'Colombo is the capital of Sri Lanka.'),
('geography', 'medium', 'What is the capital of Syria?', NULL, '["Damascus", "Djibouti", "Port Vila", "Zagreb"]', 'Damascus', 'Damascus is the capital of Syria.'),
('geography', 'medium', 'What is the capital of Papua New Guinea?', NULL, '["Port Moresby", "Maputo", "Manama", "Sana''a"]', 'Port Moresby', 'Port Moresby is the capital of Papua New Guinea.'),
('geography', 'medium', 'What is the capital of Tonga?', NULL, '["Tripoli", "Muscat", "Bratislava", "Nuku''alofa"]', 'Nuku''alofa', 'Nuku''alofa is the capital of Tonga.'),
('geography', 'medium', 'What is the capital of Japan?', NULL, '["Sucre", "Tokyo", "Kabul", "Monaco"]', 'Tokyo', 'Tokyo is the capital of Japan.'),
('geography', 'medium', 'What is the capital of Australia?', NULL, '["Conakry", "Canberra", "Kyiv", "Tallinn"]', 'Canberra', 'Canberra is the capital of Australia.'),
('geography', 'medium', 'What is the capital of Tuvalu?', NULL, '["Kabul", "Funafuti", "Brasilia", "Minsk"]', 'Funafuti', 'Funafuti is the capital of Tuvalu.'),
('geography', 'medium', 'What is the capital of Egypt?', NULL, '["Cairo", "Montevideo", "Vaduz", "Dhaka"]', 'Cairo', 'Cairo is the capital of Egypt.'),
('geography', 'medium', 'What is the capital of Mozambique?', NULL, '["Porto-Novo", "Buenos Aires", "Maputo", "Budapest"]', 'Maputo', 'Maputo is the capital of Mozambique.'),
('geography', 'medium', 'What is the capital of Angola?', NULL, '["Ljubljana", "Canberra", "Vilnius", "Luanda"]', 'Luanda', 'Luanda is the capital of Angola.'),
('geography', 'medium', 'What is the capital of Netherlands?', NULL, '["Amsterdam", "Pyongyang", "Mogadishu", "Kingston"]', 'Amsterdam', 'Amsterdam is the capital of Netherlands.'),
('geography', 'medium', 'What is the capital of Libya?', NULL, '["Tripoli", "Abuja", "Lisbon", "Tunis"]', 'Tripoli', 'Tripoli is the capital of Libya.'),
('geography', 'medium', 'What is the capital of South Korea?', NULL, '["Baghdad", "Seoul", "Brussels", "Budapest"]', 'Seoul', 'Seoul is the capital of South Korea.'),
('geography', 'medium', 'What is the capital of Saudi Arabia?', NULL, '["Nairobi", "Buenos Aires", "Warsaw", "Riyadh"]', 'Riyadh', 'Riyadh is the capital of Saudi Arabia.'),
('geography', 'medium', 'What is the capital of Zimbabwe?', NULL, '["Kingston", "Vientiane", "Harare", "Reykjavik"]', 'Harare', 'Harare is the capital of Zimbabwe.'),
('geography', 'medium', 'What is the capital of Ukraine?', NULL, '["Kyiv", "Naypyidaw", "Khartoum", "Lisbon"]', 'Kyiv', 'Kyiv is the capital of Ukraine.'),
('geography', 'medium', 'What is the capital of Spain?', NULL, '["Madrid", "Nicosia", "Athens", "Guatemala City"]', 'Madrid', 'Madrid is the capital of Spain.'),
('geography', 'hard', 'What is the capital of Turkey?', NULL, '["Valletta", "Male", "Ankara", "Lisbon"]', 'Ankara', 'Ankara is the capital of Turkey.'),
('geography', 'hard', 'What is the capital of Iraq?', NULL, '["Addis Ababa", "Canberra", "Baghdad", "Brasilia"]', 'Baghdad', 'Baghdad is the capital of Iraq.'),
('geography', 'hard', 'What is the capital of Dominican Republic?', NULL, '["Dhaka", "Ashgabat", "Santo Domingo", "Jerusalem"]', 'Santo Domingo', 'Santo Domingo is the capital of Dominican Republic.'),
('geography', 'hard', 'What is the capital of Croatia?', NULL, '["Wellington", "New Delhi", "Zagreb", "Baghdad"]', 'Zagreb', 'Zagreb is the capital of Croatia.'),
('geography', 'hard', 'What is the capital of China?', NULL, '["Beijing", "Santiago", "Abu Dhabi", "Oslo"]', 'Beijing', 'Beijing is the capital of China.'),
('geography', 'hard', 'What is the capital of Andorra?', NULL, '["Jakarta", "Andorra la Vella", "Warsaw", "Podgorica"]', 'Andorra la Vella', 'Andorra la Vella is the capital of Andorra.'),
('geography', 'hard', 'What is the capital of United Arab Emirates?', NULL, '["Nassau", "Porto-Novo", "Abu Dhabi", "Conakry"]', 'Abu Dhabi', 'Abu Dhabi is the capital of United Arab Emirates.'),
('geography', 'hard', 'What is the capital of Lithuania?', NULL, '["Wellington", "Kampala", "Port Vila", "Vilnius"]', 'Vilnius', 'Vilnius is the capital of Lithuania.'),
('geography', 'hard', 'What is the capital of Argentina?', NULL, '["Buenos Aires", "N''Djamena", "Harare", "Niamey"]', 'Buenos Aires', 'Buenos Aires is the capital of Argentina.'),
('geography', 'hard', 'What is the capital of Ireland?', NULL, '["Santiago", "Dushanbe", "Dublin", "Paris"]', 'Dublin', 'Dublin is the capital of Ireland.'),
('geography', 'hard', 'What is the capital of Jamaica?', NULL, '["Kingston", "Dodoma", "N''Djamena", "New Delhi"]', 'Kingston', 'Kingston is the capital of Jamaica.'),
('geography', 'hard', 'What is the capital of Nicaragua?', NULL, '["Canberra", "Minsk", "Riga", "Managua"]', 'Managua', 'Managua is the capital of Nicaragua.'),
('geography', 'hard', 'What is the capital of Nepal?', NULL, '["Kathmandu", "Belgrade", "Bridgetown", "Nicosia"]', 'Kathmandu', 'Kathmandu is the capital of Nepal.'),
('geography', 'hard', 'What is the capital of Barbados?', NULL, '["Bridgetown", "Bamako", "Sana''a", "Rabat"]', 'Bridgetown', 'Bridgetown is the capital of Barbados.'),
('geography', 'hard', 'What is the capital of Malaysia?', NULL, '["Moscow", "Doha", "Bucharest", "Kuala Lumpur"]', 'Kuala Lumpur', 'Kuala Lumpur is the capital of Malaysia.'),
('geography', 'hard', 'What is the capital of Gambia?', NULL, '["Seoul", "Riyadh", "Banjul", "Doha"]', 'Banjul', 'Banjul is the capital of Gambia.'),
('geography', 'hard', 'What is the capital of Maldives?', NULL, '["Sana''a", "Ankara", "Male", "Dhaka"]', 'Male', 'Male is the capital of Maldives.'),
('geography', 'hard', 'What is the capital of Thailand?', NULL, '["Bangkok", "Kathmandu", "Dakar", "Sana''a"]', 'Bangkok', 'Bangkok is the capital of Thailand.'),
('geography', 'hard', 'What is the capital of Latvia?', NULL, '["Brazzaville", "Pyongyang", "Nairobi", "Riga"]', 'Riga', 'Riga is the capital of Latvia.'),
('geography', 'hard', 'What is the capital of Slovakia?', NULL, '["Windhoek", "Seoul", "Bratislava", "Tashkent"]', 'Bratislava', 'Bratislava is the capital of Slovakia.'),
('geography', 'hard', 'What is the capital of Switzerland?', NULL, '["Santo Domingo", "Vienna", "Bern", "Singapore"]', 'Bern', 'Bern is the capital of Switzerland.'),
('geography', 'hard', 'What is the capital of United States?', NULL, '["Bratislava", "Washington D.C.", "Ngerulmud", "Addis Ababa"]', 'Washington D.C.', 'Washington D.C. is the capital of United States.'),
('geography', 'hard', 'What is the capital of Namibia?', NULL, '["Ljubljana", "Djibouti", "Windhoek", "Andorra la Vella"]', 'Windhoek', 'Windhoek is the capital of Namibia.'),
('geography', 'hard', 'What is the capital of Russia?', NULL, '["Moscow", "Djibouti", "Paris", "Roseau"]', 'Moscow', 'Moscow is the capital of Russia.'),
('geography', 'hard', 'What is the capital of Vietnam?', NULL, '["Rome", "Hanoi", "Zagreb", "Lusaka"]', 'Hanoi', 'Hanoi is the capital of Vietnam.'),
('geography', 'hard', 'What is the capital of Kazakhstan?', NULL, '["Damascus", "Tirana", "Astana", "Sucre"]', 'Astana', 'Astana is the capital of Kazakhstan.'),
('geography', 'hard', 'What is the capital of Ghana?', NULL, '["George Town", "Dodoma", "Accra", "Bamako"]', 'Accra', 'Accra is the capital of Ghana.'),
('geography', 'hard', 'What is the capital of Brazil?', NULL, '["Brasilia", "Lilongwe", "Warsaw", "Seoul"]', 'Brasilia', 'Brasilia is the capital of Brazil.'),
('geography', 'hard', 'What is the capital of Albania?', NULL, '["Riyadh", "Port Louis", "Tirana", "Naypyidaw"]', 'Tirana', 'Tirana is the capital of Albania.'),
('geography', 'hard', 'What is the capital of North Korea?', NULL, '["Pyongyang", "Beirut", "Paramaribo", "Maputo"]', 'Pyongyang', 'Pyongyang is the capital of North Korea.'),
('geography', 'hard', 'What is the capital of Mauritania?', NULL, '["Port-au-Prince", "Harare", "Kabul", "Nouakchott"]', 'Nouakchott', 'Nouakchott is the capital of Mauritania.'),
('geography', 'hard', 'What is the capital of Philippines?', NULL, '["N''Djamena", "Manila", "Libreville", "Reykjavik"]', 'Manila', 'Manila is the capital of Philippines.'),
('geography', 'hard', 'What is the capital of Tanzania?', NULL, '["Dodoma", "Djibouti", "Kathmandu", "Pretoria"]', 'Dodoma', 'Dodoma is the capital of Tanzania.'),
('geography', 'hard', 'What is the capital of Belize?', NULL, '["Hanoi", "Baku", "Managua", "Belmopan"]', 'Belmopan', 'Belmopan is the capital of Belize.'),
('geography', 'hard', 'What is the capital of Benin?', NULL, '["Funafuti", "Ottawa", "Port Moresby", "Porto-Novo"]', 'Porto-Novo', 'Porto-Novo is the capital of Benin.'),
('geography', 'hard', 'What is the capital of Sudan?', NULL, '["Baku", "Kathmandu", "Antananarivo", "Khartoum"]', 'Khartoum', 'Khartoum is the capital of Sudan.'),
('geography', 'hard', 'What is the capital of Cameroon?', NULL, '["Nouakchott", "Vaduz", "Prague", "Yaounde"]', 'Yaounde', 'Yaounde is the capital of Cameroon.'),
('geography', 'hard', 'What is the capital of Singapore?', NULL, '["Monaco", "Banjul", "Buenos Aires", "Singapore"]', 'Singapore', 'Singapore is the capital of Singapore.'),
('geography', 'hard', 'What is the capital of Monaco?', NULL, '["Baghdad", "Monaco", "Belmopan", "Gitega"]', 'Monaco', 'Monaco is the capital of Monaco.'),
('geography', 'hard', 'What is the capital of Uganda?', NULL, '["Nicosia", "Kampala", "Quito", "Riga"]', 'Kampala', 'Kampala is the capital of Uganda.'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["visible", "Visabla", "Visable", "Visible"]', 'Visible', 'The correct spelling is "Visible".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Immadiatly", "immediately", "Immediately", "Immediatly"]', 'Immediately', 'The correct spelling is "Immediately".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["gauge", "Gaga", "Gauge", "Gage"]', 'Gauge', 'The correct spelling is "Gauge".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Trualy", "truly", "Truely", "Truly"]', 'Truly', 'The correct spelling is "Truly".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Welfair", "Walfair", "welfare", "Welfare"]', 'Welfare', 'The correct spelling is "Welfare".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["accommodate", "Acommodate", "Acommodata", "Accommodate"]', 'Accommodate', 'The correct spelling is "Accommodate".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["forty", "Forty3", "Forty", "Fourty"]', 'Forty', 'The correct spelling is "Forty".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Playwrite", "playwright", "Playwright", "Playwrita"]', 'Playwright', 'The correct spelling is "Playwright".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Saparata", "Seperate", "Separate", "separate"]', 'Separate', 'The correct spelling is "Separate".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Believe", "Beleive", "Balaiva", "believe"]', 'Believe', 'The correct spelling is "Believe".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Accept", "Except", "accept", "Excapt"]', 'Accept', 'The correct spelling is "Accept".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Intaliganca", "intelligence", "Intelligence", "Inteligence"]', 'Intelligence', 'The correct spelling is "Intelligence".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Definitly", "Definitely", "definitely", "Dafinitly"]', 'Definitely', 'The correct spelling is "Definitely".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Knowlaga", "knowledge", "Knowlege", "Knowledge"]', 'Knowledge', 'The correct spelling is "Knowledge".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Therfore", "therefore", "Tharfora", "Therefore"]', 'Therefore', 'The correct spelling is "Therefore".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["foreign", "Foriegn", "Foriagn", "Foreign"]', 'Foreign', 'The correct spelling is "Foreign".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Existanca", "Existence", "existence", "Existance"]', 'Existence', 'The correct spelling is "Existence".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["definite", "Dafinata", "Definate", "Definite"]', 'Definite', 'The correct spelling is "Definite".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Naighbour", "Neighbor", "neighbor", "Neighbour"]', 'Neighbor', 'The correct spelling is "Neighbor".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Wendsday", "Wandsday", "wednesday", "Wednesday"]', 'Wednesday', 'The correct spelling is "Wednesday".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Argument", "Arguement", "Arguamant", "argument"]', 'Argument', 'The correct spelling is "Argument".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Library", "Libery", "library", "Libary"]', 'Library', 'The correct spelling is "Library".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["whether", "Whether", "Wether", "Wathar"]', 'Whether', 'The correct spelling is "Whether".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["supersede", "Supersede", "Suparcada", "Supercede"]', 'Supersede', 'The correct spelling is "Supersede".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Referred", "referred", "Refered", "Rafarad"]', 'Referred', 'The correct spelling is "Referred".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Wether", "weather", "Weather", "Wathar"]', 'Weather', 'The correct spelling is "Weather".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["leisure", "Liesure", "Leisure", "Liasura"]', 'Leisure', 'The correct spelling is "Leisure".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Seige", "Siege", "Saiga", "siege"]', 'Siege', 'The correct spelling is "Siege".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Withhold", "Withhold3", "Withold", "withhold"]', 'Withhold', 'The correct spelling is "Withhold".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["coming", "Coming", "Comming", "Coming3"]', 'Coming', 'The correct spelling is "Coming".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["absence", "Absansa", "Absense", "Absence"]', 'Absence', 'The correct spelling is "Absence".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Thourough", "thorough", "Thorough", "Thorough3"]', 'Thorough', 'The correct spelling is "Thorough".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Until", "until", "Untill", "Until3"]', 'Until', 'The correct spelling is "Until".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Gaurantee", "Gaurantaa", "guarantee", "Guarantee"]', 'Guarantee', 'The correct spelling is "Guarantee".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Occurence", "Occuranca", "Occurrence", "occurrence"]', 'Occurrence', 'The correct spelling is "Occurrence".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Millanium", "Millenium", "millennium", "Millennium"]', 'Millennium', 'The correct spelling is "Millennium".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Mispell", "Misspell", "misspell", "Mispall"]', 'Misspell', 'The correct spelling is "Misspell".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Exaad", "exceed", "Exceed", "Exeed"]', 'Exceed', 'The correct spelling is "Exceed".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Affect", "affect", "Effect", "Effact"]', 'Affect', 'The correct spelling is "Affect".'),
('spelling', 'easy', 'Which is the correct spelling?', NULL, '["Successful", "successful", "Succesful", "Succasful"]', 'Successful', 'The correct spelling is "Successful".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Dissapaar", "Disappear", "Dissapear", "disappear"]', 'Disappear', 'The correct spelling is "Disappear".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Hita", "Hite", "height", "Height"]', 'Height', 'The correct spelling is "Height".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Interruption", "interruption", "Interuption", "Intaruption"]', 'Interruption', 'The correct spelling is "Interruption".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Familiar", "Familliar", "Familiar3", "familiar"]', 'Familiar', 'The correct spelling is "Familiar".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["committee", "Comittee", "Comittaa", "Committee"]', 'Committee', 'The correct spelling is "Committee".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Indapandant", "independent", "Independant", "Independent"]', 'Independent', 'The correct spelling is "Independent".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Judgment", "judgment", "Judgement", "Judgamant"]', 'Judgment', 'The correct spelling is "Judgment".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["professor", "Professer", "Professor", "Profassar"]', 'Professor', 'The correct spelling is "Professor".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Restaraunt", "Restaurant", "Rastaraunt", "restaurant"]', 'Restaurant', 'The correct spelling is "Restaurant".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Ecstacy", "Ecstasy", "Ecstasy3", "ecstasy"]', 'Ecstasy', 'The correct spelling is "Ecstasy".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Business", "Buissness", "Buissnass", "business"]', 'Business', 'The correct spelling is "Business".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Ignoranca", "Ignorence", "ignorance", "Ignorance"]', 'Ignorance', 'The correct spelling is "Ignorance".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Agresive", "aggressive", "Agrasiva", "Aggressive"]', 'Aggressive', 'The correct spelling is "Aggressive".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Exparianca", "Experiance", "experience", "Experience"]', 'Experience', 'The correct spelling is "Experience".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Pracaad", "Precede", "Preceed", "precede"]', 'Precede', 'The correct spelling is "Precede".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Colleague", "colleague", "Colaagua", "Coleague"]', 'Colleague', 'The correct spelling is "Colleague".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Achievement", "Achiavmant", "achievement", "Achievment"]', 'Achievement', 'The correct spelling is "Achievement".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["pharaoh", "Pharaoh3", "Pharoah", "Pharaoh"]', 'Pharaoh', 'The correct spelling is "Pharaoh".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["conscience", "Conscience", "Consience", "Consianca"]', 'Conscience', 'The correct spelling is "Conscience".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["maintenance", "Maintainance", "Maintenance", "Maintainanca"]', 'Maintenance', 'The correct spelling is "Maintenance".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Apparent", "Aparent", "Aparant", "apparent"]', 'Apparent', 'The correct spelling is "Apparent".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["calendar", "Calandar", "Calendar", "Calender"]', 'Calendar', 'The correct spelling is "Calendar".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Irrelevent", "irrelevant", "Irralavant", "Irrelevant"]', 'Irrelevant', 'The correct spelling is "Irrelevant".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["schedule", "Scedule", "Schedule", "Scadula"]', 'Schedule', 'The correct spelling is "Schedule".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Mysterious", "Misterious", "Mistarious", "mysterious"]', 'Mysterious', 'The correct spelling is "Mysterious".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Questionnaire", "questionnaire", "Questionaire", "Quastionaira"]', 'Questionnaire', 'The correct spelling is "Questionnaire".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Nacasary", "Necesary", "Necessary", "necessary"]', 'Necessary', 'The correct spelling is "Necessary".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Humarous", "Humerous", "humorous", "Humorous"]', 'Humorous', 'The correct spelling is "Humorous".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Vacuum3", "vacuum", "Vaccum", "Vacuum"]', 'Vacuum', 'The correct spelling is "Vacuum".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Twalf", "twelfth", "Twelfth", "Twelf"]', 'Twelfth', 'The correct spelling is "Twelfth".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Cattegory", "category", "Cattagory", "Category"]', 'Category', 'The correct spelling is "Category".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Lollipop", "Lollypop", "lollipop", "Lollipop3"]', 'Lollipop', 'The correct spelling is "Lollipop".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["A lot", "Alot3", "Alot", "alot"]', 'Alot', 'The correct spelling is "Alot".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["publicly", "Publicly3", "Publically", "Publicly"]', 'Publicly', 'The correct spelling is "Publicly".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Finally3", "finally", "Finaly", "Finally"]', 'Finally', 'The correct spelling is "Finally".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Disappoint3", "disappoint", "Disappoint", "Dissapoint"]', 'Disappoint', 'The correct spelling is "Disappoint".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Suprise", "Surprise", "surprise", "Suprisa"]', 'Surprise', 'The correct spelling is "Surprise".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["jewelry", "Jewelry", "Jewelery", "Jawalary"]', 'Jewelry', 'The correct spelling is "Jewelry".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["recommend", "Racomand", "Recomend", "Recommend"]', 'Recommend', 'The correct spelling is "Recommend".'),
('spelling', 'medium', 'Which is the correct spelling?', NULL, '["Noticabla", "Noticable", "Noticeable", "noticeable"]', 'Noticeable', 'The correct spelling is "Noticeable".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["Hierarchy", "Heirarchy", "hierarchy", "Hairarchy"]', 'Hierarchy', 'The correct spelling is "Hierarchy".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["Farther", "Further", "Farthar", "further"]', 'Further', 'The correct spelling is "Further".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["Vegetable", "vegetable", "Vagtabla", "Vegtable"]', 'Vegetable', 'The correct spelling is "Vegetable".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["Religious", "Religous", "religious", "Raligous"]', 'Religious', 'The correct spelling is "Religious".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["Government", "Goverment", "government", "Govarmant"]', 'Government', 'The correct spelling is "Government".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["occurred", "Ocurad", "Ocured", "Occurred"]', 'Occurred', 'The correct spelling is "Occurred".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["Posassion", "Possession", "Posession", "possession"]', 'Possession', 'The correct spelling is "Possession".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["separate", "Seperate", "Saparata", "Separate"]', 'Separate', 'The correct spelling is "Separate".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["parallel", "Paralall", "Parallel", "Paralell"]', 'Parallel', 'The correct spelling is "Parallel".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["Generally", "Generaly", "generally", "Ganaraly"]', 'Generally', 'The correct spelling is "Generally".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["Manoeuvre", "Manoauvra", "maneuver", "Maneuver"]', 'Maneuver', 'The correct spelling is "Maneuver".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["grateful", "Grateful", "Greatful", "Graatful"]', 'Grateful', 'The correct spelling is "Grateful".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["Sanca", "sense", "Sense", "Sence"]', 'Sense', 'The correct spelling is "Sense".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["Vacuum3", "vacuum", "Vaccum", "Vacuum"]', 'Vacuum', 'The correct spelling is "Vacuum".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["Until", "Until3", "Untill", "until"]', 'Until', 'The correct spelling is "Until".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["typical", "Typicall", "Typical", "Typical3"]', 'Typical', 'The correct spelling is "Typical".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["Embarrass", "Embarass", "Embarrass3", "embarrass"]', 'Embarrass', 'The correct spelling is "Embarrass".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["Rhythm", "Rythm", "rhythm", "Rhythm3"]', 'Rhythm', 'The correct spelling is "Rhythm".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["Grammar", "Grammer", "grammar", "Grammar3"]', 'Grammar', 'The correct spelling is "Grammar".'),
('spelling', 'hard', 'Which is the correct spelling?', NULL, '["Drunkanass", "drunkenness", "Drunkenness", "Drunkeness"]', 'Drunkenness', 'The correct spelling is "Drunkenness".'),
('general', 'easy', 'Which ocean is the largest?', NULL, '["Atlantic Ocean", "Arctic Ocean", "Indian Ocean", "Pacific Ocean"]', 'Pacific Ocean', 'The answer is Pacific Ocean.'),
('general', 'easy', 'Which planet has the most moons?', NULL, '["Uranus", "Neptune", "Saturn", "Jupiter"]', 'Saturn', 'The answer is Saturn.'),
('general', 'easy', 'What is the chemical symbol for gold?', NULL, '["Ag", "Au", "Cu", "Fe"]', 'Au', 'The answer is Au.'),
('general', 'easy', 'What is the capital of Italy?', NULL, '["Milan", "Naples", "Florence", "Rome"]', 'Rome', 'The answer is Rome.'),
('general', 'easy', 'What is the most common element in the universe?', NULL, '["Carbon", "Oxygen", "Helium", "Hydrogen"]', 'Hydrogen', 'The answer is Hydrogen.'),
('general', 'easy', 'What is the capital of Canada?', NULL, '["Ottawa", "Toronto", "Montreal", "Vancouver"]', 'Ottawa', 'The answer is Ottawa.'),
('general', 'easy', 'Who wrote the ''Harry Potter'' series?', NULL, '["J.K. Rowling", "C.S. Lewis", "George R.R. Martin", "J.R.R. Tolkien"]', 'J.K. Rowling', 'The answer is J.K. Rowling.'),
('general', 'easy', 'Which country is home to the Kangaroo?', NULL, '["New Zealand", "Australia", "Brazil", "South Africa"]', 'Australia', 'The answer is Australia.'),
('general', 'easy', 'What is the largest mammal in the world?', NULL, '["Blue Whale", "Orca", "Elephant", "Giraffe"]', 'Blue Whale', 'The answer is Blue Whale.'),
('general', 'easy', 'Who was the first person to walk on the moon?', NULL, '["Michael Collins", "Yuri Gagarin", "Buzz Aldrin", "Neil Armstrong"]', 'Neil Armstrong', 'The answer is Neil Armstrong.'),
('general', 'easy', 'What is the largest animal on land?', NULL, '["African Elephant", "Asian Elephant", "Giraffe", "Hippopotamus"]', 'African Elephant', 'The answer is African Elephant.'),
('general', 'easy', 'What is the most populous country in the world?', NULL, '["USA", "China", "India", "Europe"]', 'China', 'The answer is China.'),
('general', 'easy', 'What is the boiling point of water at sea level?', NULL, '["90\u00b0C", "100\u00b0C", "110\u00b0C", "120\u00b0C"]', '100°C', 'The answer is 100°C.'),
('general', 'easy', 'How many bones are in the adult human body?', NULL, '["208", "206", "204", "210"]', '206', 'The answer is 206.'),
('general', 'easy', 'What is the tallest mountain in the world?', NULL, '["Mount Everest", "K2", "Mount Kilimanjaro", "Denali"]', 'Mount Everest', 'The answer is Mount Everest.'),
('general', 'easy', 'Who wrote ''Hamlet''?', NULL, '["Mark Twain", "Jane Austen", "William Shakespeare", "Charles Dickens"]', 'William Shakespeare', 'The answer is William Shakespeare.'),
('general', 'easy', 'How many continents are there?', NULL, '["8", "7", "5", "6"]', '7', 'The answer is 7.'),
('general', 'easy', 'What is the main gas found in the air we breathe?', NULL, '["Argon", "Nitrogen", "Carbon Dioxide", "Oxygen"]', 'Nitrogen', 'The answer is Nitrogen.'),
('general', 'easy', 'Who painted the Mona Lisa?', NULL, '["Pablo Picasso", "Claude Monet", "Leonardo da Vinci", "Vincent van Gogh"]', 'Leonardo da Vinci', 'The answer is Leonardo da Vinci.'),
('general', 'easy', 'What is the largest desert in the world?', NULL, '["Gobi Desert", "Arabian Desert", "Antarctic Desert", "Sahara Desert"]', 'Antarctic Desert', 'The answer is Antarctic Desert.'),
('general', 'easy', 'In which year did World War II end?', NULL, '["1944", "1943", "1946", "1945"]', '1945', 'The answer is 1945.'),
('general', 'easy', 'Which vitamin is produced when the human body is exposed to sunlight?', NULL, '["Vitamin C", "Vitamin A", "Vitamin D", "Vitamin E"]', 'Vitamin D', 'The answer is Vitamin D.'),
('general', 'easy', 'What is the capital of Japan?', NULL, '["Beijing", "Bangkok", "Seoul", "Tokyo"]', 'Tokyo', 'The answer is Tokyo.'),
('general', 'easy', 'What is the deepst part of the world''s oceans?', NULL, '["Java Trench", "Tonga Trench", "Mariana Trench", "Puerto Rico Trench"]', 'Mariana Trench', 'The answer is Mariana Trench.'),
('general', 'easy', 'What is the currency of the United Kingdom?', NULL, '["Yen", "Dollar", "Pound Sterling", "Euro"]', 'Pound Sterling', 'The answer is Pound Sterling.'),
('general', 'easy', 'What is the largest continent?', NULL, '["Asia", "Europe", "Africa", "North America"]', 'Asia', 'The answer is Asia.'),
('general', 'easy', 'What is the largest planet in our solar system?', NULL, '["Earth", "Saturn", "Jupiter", "Mars"]', 'Jupiter', 'The answer is Jupiter.'),
('general', 'easy', 'Who developed the theory of relativity?', NULL, '["Stephen Hawking", "Isaac Newton", "Nikola Tesla", "Albert Einstein"]', 'Albert Einstein', 'The answer is Albert Einstein.'),
('general', 'easy', 'Who is known as the ''Father of Computers''?', NULL, '["Alan Turing", "Bill Gates", "Steve Jobs", "Charles Babbage"]', 'Charles Babbage', 'The answer is Charles Babbage.'),
('general', 'easy', 'Who painted ''The Starry Night''?', NULL, '["Vincent van Gogh", "Pablo Picasso", "Salvador Dali", "Henri Matisse"]', 'Vincent van Gogh', 'The answer is Vincent van Gogh.'),
('general', 'medium', 'What is the primary language spoken in Brazil?', NULL, '["Portuguese", "English", "French", "Spanish"]', 'Portuguese', 'The answer is Portuguese.'),
('general', 'medium', 'Which planet is known as the Red Planet?', NULL, '["Jupiter", "Mars", "Saturn", "Venus"]', 'Mars', 'The answer is Mars.'),
('general', 'medium', 'Who invented the light bulb?', NULL, '["Nikola Tesla", "Thomas Edison", "Benjamin Franklin", "Alexander Graham Bell"]', 'Thomas Edison', 'The answer is Thomas Edison.'),
('general', 'medium', 'What is the capital of Australia?', NULL, '["Canberra", "Melbourne", "Sydney", "Perth"]', 'Canberra', 'The answer is Canberra.'),
('general', 'medium', 'Which planet is closest to the Sun?', NULL, '["Mars", "Mercury", "Earth", "Venus"]', 'Mercury', 'The answer is Mercury.'),
('general', 'medium', 'How many states are there in the United States?', NULL, '["49", "50", "48", "51"]', '50', 'The answer is 50.'),
('general', 'medium', 'What is the smallest country in the world?', NULL, '["San Marino", "Monaco", "Vatican City", "Nauru"]', 'Vatican City', 'The answer is Vatican City.'),
('general', 'medium', 'What is the capital of Germany?', NULL, '["Frankfurt", "Munich", "Hamburg", "Berlin"]', 'Berlin', 'The answer is Berlin.'),
('general', 'medium', 'Who was the first President of the United States?', NULL, '["Abraham Lincoln", "Thomas Jefferson", "John Adams", "George Washington"]', 'George Washington', 'The answer is George Washington.'),
('general', 'medium', 'Which element has the atomic number 1?', NULL, '["Hydrogen", "Oxygen", "Helium", "Carbon"]', 'Hydrogen', 'The answer is Hydrogen.'),
('general', 'medium', 'Who discovered penicillin?', NULL, '["Isaac Newton", "Marie Curie", "Alexander Fleming", "Louis Pasteur"]', 'Alexander Fleming', 'The answer is Alexander Fleming.'),
('general', 'medium', 'What is the hardest natural substance on Earth?', NULL, '["Diamond", "Quartz", "Iron", "Gold"]', 'Diamond', 'The answer is Diamond.'),
('general', 'medium', 'What is the speed of light?', NULL, '["150,000 km/s", "450,000 km/s", "299,792 km/s", "600,000 km/s"]', '299,792 km/s', 'The answer is 299,792 km/s.'),
('general', 'medium', 'Which organ is responsible for pumping blood throughout the body?', NULL, '["Liver", "Heart", "Brain", "Lungs"]', 'Heart', 'The answer is Heart.'),
('general', 'medium', 'What is the smallest prime number?', NULL, '["2", "3", "1", "5"]', '2', 'The answer is 2.'),
('general', 'medium', 'Which country is known as the Land of the Rising Sun?', NULL, '["Thailand", "South Korea", "Japan", "China"]', 'Japan', 'The answer is Japan.'),
('general', 'medium', 'Who is the author of ''The Great Gatsby''?', NULL, '["William Faulkner", "F. Scott Fitzgerald", "John Steinbeck", "Ernest Hemingway"]', 'F. Scott Fitzgerald', 'The answer is F. Scott Fitzgerald.'),
('general', 'medium', 'Which metal is liquid at room temperature?', NULL, '["Gallium", "Lead", "Mercury", "Silver"]', 'Mercury', 'The answer is Mercury.'),
('general', 'medium', 'Which gas do plants absorb from the atmosphere?', NULL, '["Hydrogen", "Carbon Dioxide", "Nitrogen", "Oxygen"]', 'Carbon Dioxide', 'The answer is Carbon Dioxide.'),
('general', 'medium', 'What is the longest river in the world?', NULL, '["Yangtze", "Mississippi", "Nile", "Amazon"]', 'Nile', 'The answer is Nile.'),
('general', 'easy', 'Placeholder question 400', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 401', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 402', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 403', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 404', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 405', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 406', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 407', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 408', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 409', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 410', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 411', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 412', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 413', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 414', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 415', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 416', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 417', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 418', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 419', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 420', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 421', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 422', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 423', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 424', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 425', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 426', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 427', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 428', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 429', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 430', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 431', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 432', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 433', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 434', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 435', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 436', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 437', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 438', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 439', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 440', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 441', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 442', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 443', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 444', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 445', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 446', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 447', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 448', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 449', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 450', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 451', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 452', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 453', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 454', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 455', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 456', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 457', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 458', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 459', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 460', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 461', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 462', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 463', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 464', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 465', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 466', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 467', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 468', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 469', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 470', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 471', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 472', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 473', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 474', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 475', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 476', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 477', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 478', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 479', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 480', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 481', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 482', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 483', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 484', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 485', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 486', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 487', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 488', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 489', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 490', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 491', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 492', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 493', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 494', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 495', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 496', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 497', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 498', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder'),
('general', 'easy', 'Placeholder question 499', NULL, '["A", "B", "C", "D"]', 'A', 'Placeholder');